version: "3.9"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    links:
      - frontend
      - database
    volumes:
      - .:/home/backend

  database:
    image: mongo
    ports:
      - "27017:27017"
    enviroment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db
  frontend:
    build: .