version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: /FRONTEND/Dockerfile
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - .:/home/app

  database:
    image: mongo
    ports:
      - "27017:27017"
    enviroment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db
